/**
 * Do not edit this file for deployment.
 *
 * 1. Copy /.env.example → /.env and fill in your keys
 * 2. Run: npm run build
 *
 * That generates supabase-config.js from your environment variables.
 * On Vercel, set the same env var names in Project Settings.
 */
