#!/usr/bin/env node
/**
 * Reads .env (local) or Vercel env vars and writes js/config/supabase-config.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '../.env') });

const url = (
  process.env.PUBLIC_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  ''
).trim();

const anonKey = (
  process.env.PUBLIC_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  ''
).trim();

const adminWriteKey = (
  process.env.SUPABASE_ADMIN_WRITE_KEY ||
  ''
).trim();

const storageBucket = (
  process.env.PUBLIC_SUPABASE_STORAGE_BUCKET ||
  process.env.SUPABASE_STORAGE_BUCKET ||
  'portfolio-media'
).trim();

const outDir = path.join(__dirname, '../js/config');
const outFile = path.join(outDir, 'supabase-config.js');

const config = {
  url: url.replace(/\/rest\/v1\/?$/i, '').replace(/\/+$/, ''),
  anonKey,
  adminWriteKey,
  storageBucket
};

if (!config.url || !config.anonKey) {
  console.warn(
    'Warning: PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY are missing.\n' +
    'Site will run in localStorage-only mode until env vars are set.'
  );
}

fs.mkdirSync(outDir, { recursive: true });

const contents = `/** Auto-generated by scripts/generate-config.js — do not edit. Use .env or Vercel env vars. */
window.SUPABASE_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outFile, contents, 'utf8');
console.log('Generated js/config/supabase-config.js');
